# permissions for end users to view persistentvolumeautocapacities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistentvolumeautocapacity-viewer-role
rules:
- apiGroups:
  - pva.kosano.io
  resources:
  - persistentvolumeautocapacities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pva.kosano.io
  resources:
  - persistentvolumeautocapacities/status
  verbs:
  - get
